export type StatusType =
   | "inProgress"
   | "completed"
   | "waiting"
   | "delayed"
   | "active"
   | "idle"
   | "maintenance"
   | "error"
   | "open"
   | "closed"

export type ProductStatusType = "inProgress" | "completed" | "waiting" | "delayed"
export type StationStatusType = "active" | "idle" | "maintenance" | "error"
export type DefectStatusType = "open" | "closed"
